spring:
  application:
    name: naeng-biseo
  datasource:
    url: jdbc:mysql://localhost:3306/naeng_biseo?useSSL=false&serverTimezone=UTC
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


swagger:
  server:
    local: http://localhost:8080

springdoc:
  swagger-ui:
    tags-sorter: alpha

jwt:
  secret: ${JWT_SECRET}
